"""Backward-compatibility shim for the Ask package.

`ask` is the canonical package and implementation authority.
`ha_ask` remains available only as a migration import path.
"""

from ask import (
    Answer,
    AskClient,
    AskSpec,
    ChoiceSpec,
    ERR_CANCELLED,
    ERR_NO_MATCH,
    ERR_NO_RESPONSE,
    ERR_TIMEOUT,
    FreeformSpec,
    ask_choice,
    ask_choice_async,
    ask_freeform,
    ask_freeform_async,
    ask_question,
    ask_question_async,
    error_kind,
    is_cancelled,
    is_match,
    is_no_match,
    is_no_response,
    is_ok,
    is_other_error,
    is_timeout,
    yes_no_spec,
)
from ask.config import Config
__all__ = [
    "AskClient",
    "ask_question",
    "ask_choice",
    "ask_freeform",
    "ask_question_async",
    "ask_choice_async",
    "ask_freeform_async",
    "AskSpec",
    "ChoiceSpec",
    "FreeformSpec",
    "Answer",
    "Config",
    "yes_no_spec",
    "ERR_NO_MATCH",
    "ERR_NO_RESPONSE",
    "ERR_TIMEOUT",
    "ERR_CANCELLED",
    "error_kind",
    "is_ok",
    "is_match",
    "is_no_match",
    "is_no_response",
    "is_timeout",
    "is_cancelled",
    "is_other_error",
]
