"""Preferred public package surface for Ask.

`ask` is the forward-looking package identity.
`ha_ask` remains available as a compatibility shim.
"""

from ha_ask import (
    Answer,
    AskClient,
    AskSpec,
    ChoiceSpec,
    ERR_CANCELLED,
    ERR_NO_MATCH,
    ERR_NO_RESPONSE,
    ERR_TIMEOUT,
    FreeformSpec,
    PlannedQuestion,
    ProbeCandidate,
    SchemaFlowResult,
    ask_choice,
    ask_choice_async,
    ask_freeform,
    ask_freeform_async,
    ask_question,
    ask_question_async,
    build_draft_report,
    error_kind,
    finalize_schema,
    is_cancelled,
    is_match,
    is_no_match,
    is_no_response,
    is_ok,
    is_other_error,
    is_timeout,
    load_demo_constants,
    plan_questions,
    run_canonical_demo,
    run_schema_flow,
    yes_no_spec,
)
from ha_ask.config import Config

__all__ = [
    "AskClient",
    "ask_question",
    "ask_choice",
    "ask_freeform",
    "ask_question_async",
    "ask_choice_async",
    "ask_freeform_async",
    "AskSpec",
    "ChoiceSpec",
    "FreeformSpec",
    "Answer",
    "Config",
    "yes_no_spec",
    "ERR_NO_MATCH",
    "ERR_NO_RESPONSE",
    "ERR_TIMEOUT",
    "ERR_CANCELLED",
    "error_kind",
    "is_ok",
    "is_match",
    "is_no_match",
    "is_no_response",
    "is_timeout",
    "is_cancelled",
    "is_other_error",
    "PlannedQuestion",
    "ProbeCandidate",
    "plan_questions",
    "finalize_schema",
    "build_draft_report",
    "run_schema_flow",
    "SchemaFlowResult",
    "load_demo_constants",
    "run_canonical_demo",
]
